[server]
# Puerto donde correrá la aplicación
port = 8501
maxUploadSize = 200
maxMessageSize = 200

# Habilitar CORS (necesario si enableXsrfProtection está activo)
enableCORS = true

# Protección XSRF
enableXsrfProtection = true

# Ejecutar en modo headless (sin abrir navegador)
headless = false

# Dirección donde se ejecuta
address = "localhost"

[browser]
# Recopilar estadísticas de uso
gatherUsageStats = false

# Abrir navegador automáticamente
serverAddress = "localhost"

[theme]
# Color principal (botones, links)
primaryColor = "#007bff"

# Color de fondo principal
backgroundColor = "#FFFFFF"

# Color de fondo secundario (sidebar)
secondaryBackgroundColor = "#f8f9fa"

# Color del texto
textColor = "#24282a"

# Fuente (opciones: "sans serif", "serif", "monospace")
font = "sans serif"

[client]
# Mostrar detalles de errores
showErrorDetails = true

# Mostrar barra de herramientas
toolbarMode = "auto"

# Mostrar sidebar por defecto
showSidebarNavigation = true

[runner]
# Habilitar magic commands (%%, !)
magicEnabled = true

# Instalar watchdog para auto-reload
fastReruns = true

[logger]
# Nivel de log
level = "info"

# Format de mensajes
messageFormat = "%(asctime)s %(message)s"